// Created by Maxwolf (bigmaxwolf.com) 
// Timestamp 01/03/2016@1:50 AM

using System;
using System.Text;
using WolfCurses.Window;
using WolfCurses.Window.Form;
using WolfCurses.Window.Form.Input;

namespace OregonTrailDotNet.Window.Graveyard
{
    /// <summary>
    ///     Form that is used to show data about a tombstone. It will look for a tombstone at the current vehicle odometer, if
    ///     none if found one will be generated by the user data.
    /// </summary>
    [ParentWindow(typeof(Graveyard))]
    public sealed class TombstoneView : InputForm<TombstoneInfo>
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="TombstoneView" /> class.
        ///     This constructor will be used by the other one
        /// </summary>
        /// <param name="window">The window.</param>
        // ReSharper disable once UnusedMember.Global
        public TombstoneView(IWindow window) : base(window)
        {
        }

        /// <summary>
        ///     Fired when dialog prompt is attached to active game Windows and would like to have a string returned.
        /// </summary>
        /// <returns>
        ///     The <see cref="string" />.
        /// </returns>
        protected override string OnDialogPrompt()
        {
            // Check if the tombstone manager returned anything, if not then check for user data it's player death then.
            var tombstone = new StringBuilder();

            // A living party is stopping to read a grave they just came across on the trail.
            if (GameSimulationApp.Instance.Vehicle.PassengerLivingCount > 0)
            {
                // Show the grave the party just crossed. Fall back to an exact-odometer lookup on the off chance we landed
                // right on the mile marker without the crossing check recording it first.
                var foundTombstone = GameSimulationApp.Instance.Tombstone.Encountered;
                if (foundTombstone == null)
                    GameSimulationApp.Instance.Tombstone.FindTombstone(
                        GameSimulationApp.Instance.Vehicle.Odometer,
                        out foundTombstone);

                tombstone.AppendLine($"{Environment.NewLine}{foundTombstone}");
            }
            else
            {
                tombstone.AppendLine($"{Environment.NewLine}{UserData.Tombstone}");

                // Adds the underlying reason for the games failure if it was not obvious to the player by now.
                tombstone.AppendLine("All the members of");
                tombstone.AppendLine("your party have");
                tombstone.AppendLine($"died.{Environment.NewLine}");

                // Show how far the party made it before they perished.
                tombstone.AppendLine($"You traveled {GameSimulationApp.Instance.Vehicle.Odometer:N0} miles.{Environment.NewLine}");
            }

            // Write out the tombstone text and epitaph message to the game window.
            return tombstone.ToString();
        }

        /// <summary>
        ///     Fired when the dialog receives favorable input and determines a response based on this. From this method it is
        ///     common to attach another state, or remove the current state based on the response.
        /// </summary>
        /// <param name="reponse">The response the dialog parsed from simulation input buffer.</param>
        protected override void OnDialogResponse(DialogResponse reponse)
        {
            // Determine if we are showing the player a tombstone because they died.
            if (GameSimulationApp.Instance.Vehicle.PassengerLivingCount <= 0)
            {
                // Completely resets the game to default state it was in when it first started.
                UserData.ClearTombstone();
                GameSimulationApp.Instance.Restart();
                return;
            }

            // Return to travel mode menu if we are just looking at some other dead guy grave.
            ParentWindow.RemoveWindowNextTick();
        }
    }
}